name: admin_pannel
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.4.0
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+4
  file_picker: ^10.1.9
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  image_picker: ^1.1.2
  path: ^1.9.1
  mime: ^2.0.0
  http_parser: ^4.1.2
  excel: ^4.0.6
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  universal_html: ^2.2.4
  bloc: ^9.0.0
  path_provider: ^2.1.5
  web_socket_channel: ^3.0.3
  audioplayers: ^6.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_doc_scanner: ^0.0.16
  permission_handler: ^12.0.1
  open_filex: ^4.7.0
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_logo.png"
    background_color: "#ffffff"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icons/app_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_logo.png"


flutter:


  uses-material-design: true

  assets:
    - assets/images/trendy_logo.png
    - assets/images/google_logo.png
    - assets/images/apple_logo.png
    - assets/lottie/shopping.json
    - assets/lottie/auth.json
    - assets/sounds/order_alert.mp3


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
